- id: '1779799375322'
  alias: Reolink Front Door Recording
  description: ''
  triggers:
  - trigger: state
    entity_id: binary_sensor.front_door_person
    to: 'on'
  conditions: []
  actions:
  - action: telegram_bot.send_message
    data:
      message: 'Recording started: Front Door'
      entity_id:
      - notify.skyline_home_kanstantsin
      - notify.skyline_home_aleksandr
  - parallel:
    - action: camera_record_services.camera_start_recording
      data:
        entity_id: camera.front_door_clear
        filename: /media/cam/{{ now().strftime('%Y%m%d_%H-%M-%S') }}_front-door.mp4
        duration: 3600
        lookback: 5
        stop_state_id: binary_sensor.front_door_person_detection_delayed
        stop_state_value: 'off'
        extend_running_task: true
    - repeat:
        while:
        - condition: state
          entity_id: binary_sensor.front_door_person_detection_delayed
          state: 'on'
        sequence:
        - action: camera.snapshot
          data:
            filename: /config/front_door_snap.jpg
          target:
            entity_id: camera.front_door_snapshots_clear
        - action: telegram_bot.send_photo
          data:
            file: /config/front_door_snap.jpg
            entity_id:
            - notify.skyline_home_kanstantsin
            - notify.skyline_home_aleksandr
            caption: front door
        - action: shell_command.delete_front_door_snap
        - delay:
            seconds: 5
  mode: single
- id: '2779799375322'
  alias: Reolink Saloon Recording
  description: ''
  triggers:
  - trigger: state
    entity_id: binary_sensor.saloon_person
    to: 'on'
  conditions: []
  actions:
  - action: telegram_bot.send_message
    data:
      message: 'Recording started: Saloon'
      entity_id:
      - notify.skyline_home_kanstantsin
      - notify.skyline_home_aleksandr
  - parallel:
    - action: camera_record_services.camera_start_recording
      data:
        entity_id: camera.saloon_clear
        filename: /media/cam/{{ now().strftime('%Y%m%d_%H-%M-%S') }}_saloon.mp4
        duration: 3600
        lookback: 5
        stop_state_id: binary_sensor.saloon_person_detection_delayed
        stop_state_value: 'off'
        extend_running_task: true
    - repeat:
        while:
        - condition: state
          entity_id: binary_sensor.saloon_person_detection_delayed
          state: 'on'
        sequence:
        - action: camera.snapshot
          data:
            filename: /config/saloon_snap.jpg
          target:
            entity_id: camera.saloon_snapshots_clear
        - action: telegram_bot.send_photo
          data:
            file: /config/saloon_snap.jpg
            entity_id:
            - notify.skyline_home_kanstantsin
            - notify.skyline_home_aleksandr
            caption: saloon
        - action: shell_command.delete_saloon_snap
        - delay:
            seconds: 5
  mode: single
- id: '3779799375322'
  alias: Reolink Bedroom Recording
  description: ''
  triggers:
  - trigger: state
    entity_id: binary_sensor.bedroom_person
    to: 'on'
  conditions: []
  actions:
  - action: telegram_bot.send_message
    data:
      message: 'Recording started: Bedroom'
      entity_id:
      - notify.skyline_home_kanstantsin
      - notify.skyline_home_aleksandr
  - parallel:
    - action: camera_record_services.camera_start_recording
      data:
        entity_id: camera.bedroom_clear
        filename: /media/cam/{{ now().strftime('%Y%m%d_%H-%M-%S') }}_bedroom.mp4
        duration: 3600
        lookback: 5
        stop_state_id: binary_sensor.bedroom_person_detection_delayed
        stop_state_value: 'off'
        extend_running_task: true
    - repeat:
        while:
        - condition: state
          entity_id: binary_sensor.bedroom_person_detection_delayed
          state: 'on'
        sequence:
        - action: camera.snapshot
          data:
            filename: /config/bedroom_snap.jpg
          target:
            entity_id: camera.bedroom_snapshots_clear
        - action: telegram_bot.send_photo
          data:
            file: /config/bedroom_snap.jpg
            entity_id:
            - notify.skyline_home_kanstantsin
            - notify.skyline_home_aleksandr
            caption: bedroom
        - action: shell_command.delete_bedroom_snap
        - delay:
            seconds: 5
  mode: single
- id: '1779799375323'
  alias: Reolink Front Door Recording Stopped
  description: ''
  triggers:
  - platform: state
    entity_id: binary_sensor.front_door_person_detection_delayed
    to: 'off'
  conditions: []
  actions:
  - action: telegram_bot.send_message
    data:
      message: 'Recording stopped: Front Door'
      entity_id:
      - notify.skyline_home_kanstantsin
      - notify.skyline_home_aleksandr
  mode: single
- id: '2779799375323'
  alias: Reolink Saloon Recording Stopped
  description: ''
  triggers:
  - platform: state
    entity_id: binary_sensor.saloon_person_detection_delayed
    to: 'off'
  conditions: []
  actions:
  - action: telegram_bot.send_message
    data:
      message: 'Recording stopped: Saloon'
      entity_id:
      - notify.skyline_home_kanstantsin
      - notify.skyline_home_aleksandr
  mode: single
- id: '3779799375323'
  alias: Reolink Bedroom Recording Stopped
  description: ''
  triggers:
  - platform: state
    entity_id: binary_sensor.bedroom_person_detection_delayed
    to: 'off'
  conditions: []
  actions:
  - action: telegram_bot.send_message
    data:
      message: 'Recording stopped: Bedroom'
      entity_id:
      - notify.skyline_home_kanstantsin
      - notify.skyline_home_aleksandr
  mode: single
- id: '1780785372930'
  alias: Cleanup Old Video
  description: ''
  triggers:
  - trigger: time_pattern
    hours: '1'
  conditions: []
  actions:
  - action: shell_command.delete_old_recordings
    metadata: {}
    data: {}
  mode: single
