default_config:
logger:
  default: info
  logs:
    homeassistant.components.onvif: info
    homeassistant.components.automation: debug
    custom_components.camera_record_services: debug
    homeassistant.components.binary_sensor: debug

automation: !include automations.yaml
template: !include templates.yaml

shell_command:
  delete_old_recordings: "echo \"--- $(date) Reolink ---\" >> /media/logs/ha_video_cleanup.log && find /media/cam -name '*.mp4' -mmin +1440 -delete -print >> /media/logs/ha_video_cleanup.log 2>&1"
  delete_front_door_snap: "rm -f /config/front_door_snap.jpg"
  delete_saloon_snap: "rm -f /config/saloon_snap.jpg"
  delete_bedroom_snap: "rm -f /config/bedroom_snap.jpg"

homeassistant:
  allowlist_external_dirs:
    - /tmp
    - /config
